config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :name, :age, :gender, :designation, presence: true
    validates :age, numericality: {message: "should be a number"},
    :unless => Proc.new {|data| data.age.blank?}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

def index
    @employees = Employee.all
end

def new
    @employee = Employee.new
    @buttonName = "ADD EMPLOYEE"
end

def show
    @employee = Employee.find(params[:id])
end

def create
    @employee = Employee.new(employee_params)
 
  if @employee.save
    redirect_to @employee
  else
    render 'new'
  end
end

def edit
  @employee = Employee.find(params[:id])
  @buttonName = "UPDATE EMPLOYEE"
end

def update
  @employee = Employee.find(params[:id])

  if @employee.update(employee_params)
    redirect_to @employee
  else
    render 'edit'
  end

end

def destroy
  @employee = Employee.find(params[:id])
  @employee.destroy
  
  redirect_to employees_path
end

private
  def employee_params
    params.require(:employee).permit(:name, :age, :gender, :designation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: @employee, :html => {:autocomplete => "on"}, local: true do |form| %>

    <% if @employee.errors.any? %>
    <div class="error_explanation">
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <table class = "edit_table">
        <tr>
            <td><%= form.label :name %></td>
            <td><%= form.text_field :name %></td>
        </tr>
        <tr>
            <td><%= form.label :age %><br></td>
            <td><%= form.text_field :age %></td>
        </tr>
        <tr>
            <td><%= form.label :gender %><br></td>
            <td><%= form.text_field :gender %></td>
        </tr>
        <tr>
            <td><%= form.label :designation %><br></td>
            <td><%= form.text_field :designation %></td>
        </tr>
    </table>
    <p>
      <%= form.submit @buttonName %>
    </p>
  <% end %>
  
  <%= link_to 'Home', employees_path %>

app/views/employees/edit.html.erb
<h2>Editing Employee:</h2>
<%= render 'form' %>

app/views/employees/index.html.erb
<h2>Employees list</h2>
 
<table class = "index_table">
  <tr>
    <th>S.NO</th>
    <th>NAME</th>
    <th>AGE</th>
    <th>GENDER</th>
    <th>DESIGNATION</th>
  </tr>
 

  <% count = 1 %>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= count %>
      <td><%= employee.name %></td>
      <td><%= employee.age %></td>
      <td><%= employee.gender %></td>
      <td><%= employee.designation %></td>
      <td><%= link_to 'View', employee_path(employee) %></td>
      <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
      <td><%= link_to 'Destroy', employee_path(employee),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% count = count + 1 %>
  <% end %>
</table>
<p>
<%= link_to 'Add Employee', new_employee_path %>

app/views/employees/new.html.erb
<h2>Adding Employee:</h2>
<%= render 'form' %>

app/views/employees/show.html.erb
<p>
<strong>Name:</strong>
<%= @employee.name %>
</p>

<p>
<strong>Age:</strong>
<%= @employee.age %>
</p>

<p>
<strong>Gender:</strong>
<%= @employee.gender %>
</p>

<p>
<strong>Designation:</strong>
<%= @employee.designation %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %>
<%= link_to 'Home', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Management System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header><h1>Employee Management System</h1></header>
    <%= yield %>
  </body>
</html>